apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: inventoryapp-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - inventoryapp.example.com
    secretName: inventoryapp-tls
  rules:
  - host: inventoryapp.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: inventoryapp-web
            port:
              number: 80
