# -*- coding: utf-8 -*-
"""
Utils Package for InventoryApp
Centralizes utility functions, constants, and exceptions
"""

from .constants import (
    UserRole,
    ItemStatus,
    TicketStatus,
    TicketPriorityLevel,
    TicketCategory,
    MaintenanceStatus,
    NotificationType,
    Permission,
    AppSettings,
    HTTPStatus,
    AuditAction,
    DepreciationRate,
    DateFormat,
    WebhookColor,
)

from .exceptions import (
    InventoryAppException,
    ResourceNotFoundException,
    ItemNotFoundException,
    UserNotFoundException,
    LoanNotFoundException,
    TicketNotFoundException,
    CategoryNotFoundException,
    LocationNotFoundException,
    PermissionDeniedException,
    AuthenticationRequiredException,
    InvalidCredentialsException,
    ValidationException,
    InvalidInputException,
    MissingRequiredFieldException,
    DuplicateResourceException,
    ItemNotAvailableException,
    LoanAlreadyReturnedException,
    ReservationConflictException,
    ExternalServiceException,
    DellAPIException,
    EmailServiceException,
    InvalidFileTypeException,
    FileTooLargeException,
    DatabaseException,
    RateLimitExceededException,
    ConfigurationException,
    ImportException,
    ExportException,
)

__all__ = [
    # Constants
    'UserRole',
    'ItemStatus',
    'TicketStatus',
    'TicketPriorityLevel',
    'TicketCategory',
    'MaintenanceStatus',
    'NotificationType',
    'Permission',
    'AppSettings',
    'HTTPStatus',
    'AuditAction',
    'DepreciationRate',
    'DateFormat',
    'WebhookColor',
    # Exceptions
    'InventoryAppException',
    'ResourceNotFoundException',
    'ItemNotFoundException',
    'UserNotFoundException',
    'LoanNotFoundException',
    'TicketNotFoundException',
    'CategoryNotFoundException',
    'LocationNotFoundException',
    'PermissionDeniedException',
    'AuthenticationRequiredException',
    'InvalidCredentialsException',
    'ValidationException',
    'InvalidInputException',
    'MissingRequiredFieldException',
    'DuplicateResourceException',
    'ItemNotAvailableException',
    'LoanAlreadyReturnedException',
    'ReservationConflictException',
    'ExternalServiceException',
    'DellAPIException',
    'EmailServiceException',
    'InvalidFileTypeException',
    'FileTooLargeException',
    'DatabaseException',
    'RateLimitExceededException',
    'ConfigurationException',
    'ImportException',
    'ExportException',
]
